# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 06:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200, verbose_name='text')),
                ('votes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'choices',
                'ordering': ['votes'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2016, 5, 19, 7, 57, 52, 187247, tzinfo=utc))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2016, 5, 20, 6, 57, 52, 187565, tzinfo=utc))),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'db_table': 'polls',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
    ]
