# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 23:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160518_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ended_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 23, 42, 55, 429099, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 23, 42, 58, 869080, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
